[2025-06-08T20:24:40.264+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multi_region_processor.process_region_asia.process_customers_asia manual__2025-06-08T20:24:20.634976+00:00 [queued]>
[2025-06-08T20:24:40.284+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multi_region_processor.process_region_asia.process_customers_asia manual__2025-06-08T20:24:20.634976+00:00 [queued]>
[2025-06-08T20:24:40.285+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-06-08T20:24:40.320+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_region_asia.process_customers_asia> on 2025-06-08 20:24:20.634976+00:00
[2025-06-08T20:24:40.329+0000] {standard_task_runner.py:60} INFO - Started process 200574 to run task
[2025-06-08T20:24:40.332+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-06-08T20:24:40.340+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multi_region_processor', 'process_region_asia.process_customers_asia', 'manual__2025-06-08T20:24:20.634976+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/master2.py', '--cfg-path', '/tmp/tmp4aocu78j']
[2025-06-08T20:24:40.343+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask process_region_asia.process_customers_asia
[2025-06-08T20:24:40.412+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-08T20:24:40.514+0000] {task_command.py:423} INFO - Running <TaskInstance: multi_region_processor.process_region_asia.process_customers_asia manual__2025-06-08T20:24:20.634976+00:00 [running]> on host 098d7b977cb8
[2025-06-08T20:24:40.851+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='multi_region_processor' AIRFLOW_CTX_TASK_ID='process_region_asia.process_customers_asia' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T20:24:20.634976+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T20:24:20.634976+00:00'
[2025-06-08T20:24:40.867+0000] {logging_mixin.py:188} INFO - Processing customers for region asia
[2025-06-08T20:25:09.201+0000] {logging_mixin.py:188} INFO - âœ… Successfully processed 50 records for customers in asia
[2025-06-08T20:32:37.892+0000] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2025-06-08T20:32:38.362+0000] {process_utils.py:131} INFO - Sending 15 to group 200574. PIDs of all processes in the group: [200574]
[2025-06-08T20:32:38.422+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 200574
[2025-06-08T20:32:38.734+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-08T20:32:39.940+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/master2.py", line 392, in process_table
    df_transformed.write.mode("overwrite").parquet(output_path)
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/sql/session.py", line 1796, in stop
    self._sc.stop()
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/context.py", line 666, in stop
    self._accumulatorServer.shutdown()
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/accumulators.py", line 316, in shutdown
    SocketServer.TCPServer.shutdown(self)
  File "/usr/local/lib/python3.10/socketserver.py", line 252, in shutdown
    self.__is_shut_down.wait()
  File "/usr/local/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-06-08T20:32:40.023+0000] {logging_mixin.py:188} WARNING - ----------------------------------------
[2025-06-08T20:32:40.025+0000] {logging_mixin.py:188} WARNING - Exception occurred during processing of request from ('127.0.0.1', 47112)
[2025-06-08T20:32:40.032+0000] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2025-06-08T20:32:40.037+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
[2025-06-08T20:32:40.038+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
[2025-06-08T20:32:40.038+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
[2025-06-08T20:32:40.038+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
[2025-06-08T20:32:40.039+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/accumulators.py", line 295, in handle
    poll(accum_updates)
[2025-06-08T20:32:40.039+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/accumulators.py", line 267, in poll
    if self.rfile in r and func():
[2025-06-08T20:32:40.039+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/accumulators.py", line 271, in accum_updates
    num_updates = read_int(self.rfile)
[2025-06-08T20:32:40.040+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/serializers.py", line 596, in read_int
    raise EOFError
[2025-06-08T20:32:40.040+0000] {logging_mixin.py:188} WARNING - EOFError
[2025-06-08T20:32:40.041+0000] {logging_mixin.py:188} WARNING - ----------------------------------------
[2025-06-08T20:32:40.066+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=multi_region_processor, task_id=process_region_asia.process_customers_asia, execution_date=20250608T202420, start_date=20250608T202440, end_date=20250608T203240
[2025-06-08T20:32:41.266+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 18 for task process_region_asia.process_customers_asia (Task received SIGTERM signal; 200574)
[2025-06-08T20:32:41.329+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=200574, status='terminated', exitcode=1, started='20:24:40') (200574) terminated with exit code 1
[2025-06-08T20:32:41.335+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 143
[2025-06-08T20:32:41.680+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
