[2025-06-11T07:28:02.698+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multi_region_ods_merge_v2.ods_merge_group.merge_marketing_campaigns manual__2025-06-11T07:27:59.883458+00:00 [queued]>
[2025-06-11T07:28:02.720+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multi_region_ods_merge_v2.ods_merge_group.merge_marketing_campaigns manual__2025-06-11T07:27:59.883458+00:00 [queued]>
[2025-06-11T07:28:02.721+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-11T07:28:02.755+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): ods_merge_group.merge_marketing_campaigns> on 2025-06-11 07:27:59.883458+00:00
[2025-06-11T07:28:02.768+0000] {standard_task_runner.py:60} INFO - Started process 17564 to run task
[2025-06-11T07:28:02.774+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multi_region_ods_merge_v2', 'ods_merge_group.merge_marketing_campaigns', 'manual__2025-06-11T07:27:59.883458+00:00', '--job-id', '1471', '--raw', '--subdir', 'DAGS_FOLDER/master_ods_dag.py', '--cfg-path', '/tmp/tmpsftmhf36']
[2025-06-11T07:28:02.782+0000] {standard_task_runner.py:88} INFO - Job 1471: Subtask ods_merge_group.merge_marketing_campaigns
[2025-06-11T07:28:02.945+0000] {task_command.py:423} INFO - Running <TaskInstance: multi_region_ods_merge_v2.ods_merge_group.merge_marketing_campaigns manual__2025-06-11T07:27:59.883458+00:00 [running]> on host 62842a22292a
[2025-06-11T07:28:03.861+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='multi_region_ods_merge_v2' AIRFLOW_CTX_TASK_ID='ods_merge_group.merge_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T07:27:59.883458+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T07:27:59.883458+00:00'
[2025-06-11T07:28:03.864+0000] {connection.py:486} INFO - Snowflake Connector for Python Version: 3.15.0, Python Version: 3.10.13, Platform: Linux-6.11.0-26-generic-x86_64-with-glibc2.36
[2025-06-11T07:28:03.865+0000] {connection.py:1391} INFO - Connecting to GLOBAL Snowflake domain
[2025-06-11T07:28:06.634+0000] {logging_mixin.py:188} INFO - Successfully connected to Snowflake via snowflake.connector.
[2025-06-11T07:28:06.634+0000] {logging_mixin.py:188} INFO - Running merge for marketing_campaigns...
[2025-06-11T07:28:07.041+0000] {logging_mixin.py:188} INFO - Error running merge for marketing_campaigns: 000904 (42000): 01bcf400-0305-97a6-0008-654b001322ba: SQL compilation error: error line 83 at position 8
invalid identifier 'SRC.BUDGET_USD'
[2025-06-11T07:28:07.625+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/master_ods_dag.py", line 171, in merge_table
    run_merge_query(t)
  File "/opt/airflow/dags/master_ods_dag.py", line 150, in run_merge_query
    cursor.execute(merge_sql)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/cursor.py", line 1134, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 279, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 334, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 210, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000904 (42000): 01bcf400-0305-97a6-0008-654b001322ba: SQL compilation error: error line 83 at position 8
invalid identifier 'SRC.BUDGET_USD'
[2025-06-11T07:28:07.641+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=multi_region_ods_merge_v2, task_id=ods_merge_group.merge_marketing_campaigns, execution_date=20250611T072759, start_date=20250611T072802, end_date=20250611T072807
[2025-06-11T07:28:07.660+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1471 for task ods_merge_group.merge_marketing_campaigns (000904 (42000): 01bcf400-0305-97a6-0008-654b001322ba: SQL compilation error: error line 83 at position 8
invalid identifier 'SRC.BUDGET_USD'; 17564)
[2025-06-11T07:28:07.683+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-11T07:28:07.712+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
