[2025-06-09T07:56:53.328+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multi_region_processor_7.process_region_asia.process_discounts_asia manual__2025-06-09T07:54:44.650319+00:00 [queued]>
[2025-06-09T07:56:53.340+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multi_region_processor_7.process_region_asia.process_discounts_asia manual__2025-06-09T07:54:44.650319+00:00 [queued]>
[2025-06-09T07:56:53.341+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-06-09T07:56:53.355+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_region_asia.process_discounts_asia> on 2025-06-09 07:54:44.650319+00:00
[2025-06-09T07:56:53.362+0000] {standard_task_runner.py:60} INFO - Started process 92802 to run task
[2025-06-09T07:56:53.365+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'multi_region_processor_7', 'process_region_asia.process_discounts_asia', 'manual__2025-06-09T07:54:44.650319+00:00', '--job-id', '620', '--raw', '--subdir', 'DAGS_FOLDER/master2.py', '--cfg-path', '/tmp/tmpx0r1barc']
[2025-06-09T07:56:53.366+0000] {standard_task_runner.py:88} INFO - Job 620: Subtask process_region_asia.process_discounts_asia
[2025-06-09T07:56:53.385+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-09T07:56:53.438+0000] {task_command.py:423} INFO - Running <TaskInstance: multi_region_processor_7.process_region_asia.process_discounts_asia manual__2025-06-09T07:54:44.650319+00:00 [running]> on host afcdbcf38bc0
[2025-06-09T07:56:53.590+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='multi_region_processor_7' AIRFLOW_CTX_TASK_ID='process_region_asia.process_discounts_asia' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T07:54:44.650319+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T07:54:44.650319+00:00'
[2025-06-09T07:56:59.088+0000] {logging_mixin.py:188} INFO - Processing discounts for region asia
[2025-06-09T07:57:09.650+0000] {logging_mixin.py:188} INFO - +-----------+-------------+--------------------+-------------+--------------+--------------------+--------------------+-----------+-----------+-------------------+-------------------+---------+-------------------+-------+--------+
|discount_id|discount_code|       discount_name|discount_type|discount_value|minimum_order_amount|maximum_order_amount|usage_limit|usage_count|         start_date|           end_date|is_active|         created_at|_region| _source|
+-----------+-------------+--------------------+-------------+--------------+--------------------+--------------------+-----------+-----------+-------------------+-------------------+---------+-------------------+-------+--------+
|          1|    WELCOME10|New Customer Welcome|   percentage|          10.0|                5000|               10000|       1000|        234|2024-01-01 00:00:00|2024-12-31 00:00:00|     true|2024-02-25 11:50:35|   asia|postgres|
|          2|     SPRING25| Spring Sale 25% Off|   percentage|          25.0|               10000|               20000|        500|        156|2024-03-01 00:00:00|2024-03-31 00:00:00|    false|2024-02-26 00:00:00|   asia|postgres|
|          3|     FREESHIP|       Free Shipping|     shipping|           0.0|                8000|                1500|       2000|        567|2024-03-01 00:00:00|2024-12-31 00:00:00|     true|2024-02-27 00:00:00|   asia|postgres|
|          4|     SAVE5000|       Save 5000 Yen|        fixed|        5000.0|               20000|                5000|        300|         89|               NULL|               NULL|    false|               NULL|   asia|postgres|
|          5|   BLACKFRI30|Black Friday 30% Off|   percentage|          30.0|               15000|               30000|       1000|        678|2024-11-25 00:00:00|2024-11-29 00:00:00|    false|2024-02-29 00:00:00|   asia|postgres|
|          6|    STUDENT15|    Student Discount|   percentage|          15.0|                3000|               15000|          0|        123|2024-01-01 00:00:00|2024-12-31 00:00:00|     true|2024-03-01 12:35:30|   asia|postgres|
|          7|      LOYAL25|Loyalty Member 25...|   percentage|          25.0|               10000|               25000|        500|        234|2024-01-01 00:00:00|2024-12-31 00:00:00|     true|2024-03-02 00:00:00|   asia|postgres|
|          8|     SUMMER20|      Summer Special|   percentage|          20.0|                8000|               12000|        750|        345|2024-06-01 00:00:00|2024-08-31 00:00:00|     true|2024-03-03 00:00:00|   asia|postgres|
|          9|     FIRST100| First 100 Customers|        fixed|        2500.0|               10000|                2500|        100|        100|               NULL|               NULL|    false|               NULL|   asia|postgres|
|         10|    WEEKEND10|     Weekend Special|   percentage|          10.0|                6000|                8000|          0|        456|2024-01-01 00:00:00|2024-12-31 00:00:00|     true|2024-05-03 00:00:00|   asia|postgres|
+-----------+-------------+--------------------+-------------+--------------+--------------------+--------------------+-----------+-----------+-------------------+-------------------+---------+-------------------+-------+--------+
only showing top 10 rows
[2025-06-09T07:57:11.187+0000] {logging_mixin.py:188} INFO - Inserting into snowflake
[2025-06-09T07:57:40.595+0000] {logging_mixin.py:188} INFO - Error processing discounts for asia: An error occurred while calling o153.save.
: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Schema 'RETAIL_DWH.ASIA' does not exist or not authorized.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:451)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:354)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:487)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:198)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:135)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:767)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:677)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:238)
	at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:117)
	at net.snowflake.spark.snowflake.JDBCWrapper.$anonfun$executePreparedQueryInterruptibly$1(SnowflakeJDBCWrapper.scala:205)
	at net.snowflake.spark.snowflake.JDBCWrapper.$anonfun$executeInterruptibly$2(SnowflakeJDBCWrapper.scala:252)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-06-09T07:57:40.953+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/master2.py", line 194, in process_table
    write_to_snowflake(df_transformed, table_name=table, region=region, sf_options=SF_OPTIONS)
  File "/opt/airflow/dags/master2.py", line 184, in write_to_snowflake
    .save()
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/sql/readwriter.py", line 1461, in save
    self._jwrite.save()
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
    return f(*a, **kw)
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o153.save.
: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Schema 'RETAIL_DWH.ASIA' does not exist or not authorized.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:451)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:354)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:487)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:198)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:135)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:767)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:677)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:238)
	at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:117)
	at net.snowflake.spark.snowflake.JDBCWrapper.$anonfun$executePreparedQueryInterruptibly$1(SnowflakeJDBCWrapper.scala:205)
	at net.snowflake.spark.snowflake.JDBCWrapper.$anonfun$executeInterruptibly$2(SnowflakeJDBCWrapper.scala:252)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[2025-06-09T07:57:40.981+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=multi_region_processor_7, task_id=process_region_asia.process_discounts_asia, execution_date=20250609T075444, start_date=20250609T075653, end_date=20250609T075740
[2025-06-09T07:57:41.008+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 620 for task process_region_asia.process_discounts_asia (An error occurred while calling o153.save.
: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Schema 'RETAIL_DWH.ASIA' does not exist or not authorized.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:127)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:67)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:451)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:354)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:487)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:198)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:135)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:767)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:677)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:238)
	at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:117)
	at net.snowflake.spark.snowflake.JDBCWrapper.$anonfun$executePreparedQueryInterruptibly$1(SnowflakeJDBCWrapper.scala:205)
	at net.snowflake.spark.snowflake.JDBCWrapper.$anonfun$executeInterruptibly$2(SnowflakeJDBCWrapper.scala:252)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
; 92802)
[2025-06-09T07:57:41.031+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-09T07:57:41.073+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
