[2025-06-10T12:40:53.559+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_performance_to_snowflake.process_marketing_data manual__2025-06-10T12:39:37.213987+00:00 [queued]>
[2025-06-10T12:40:53.566+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_performance_to_snowflake.process_marketing_data manual__2025-06-10T12:39:37.213987+00:00 [queued]>
[2025-06-10T12:40:53.566+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-10T12:40:53.578+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): process_marketing_data> on 2025-06-10 12:39:37.213987+00:00
[2025-06-10T12:40:53.588+0000] {standard_task_runner.py:60} INFO - Started process 1735 to run task
[2025-06-10T12:40:53.590+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'marketing_performance_to_snowflake', 'process_marketing_data', 'manual__2025-06-10T12:39:37.213987+00:00', '--job-id', '1092', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_snowflake_dag.py', '--cfg-path', '/tmp/tmpue1n8alu']
[2025-06-10T12:40:53.591+0000] {standard_task_runner.py:88} INFO - Job 1092: Subtask process_marketing_data
[2025-06-10T12:40:53.606+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-10T12:40:53.641+0000] {task_command.py:423} INFO - Running <TaskInstance: marketing_performance_to_snowflake.process_marketing_data manual__2025-06-10T12:39:37.213987+00:00 [running]> on host 2a1e0c00bfff
[2025-06-10T12:40:53.741+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='marketing_performance_to_snowflake' AIRFLOW_CTX_TASK_ID='process_marketing_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-10T12:39:37.213987+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-10T12:39:37.213987+00:00'
[2025-06-10T12:40:53.742+0000] {logging_mixin.py:188} INFO - Starting marketing performance data processing for date: 2025-06-08
[2025-06-10T12:40:56.914+0000] {logging_mixin.py:188} INFO - Processing csv for region 2025-06-08
[2025-06-10T12:40:56.916+0000] {logging_mixin.py:188} INFO - Error processing marketing data: local variable 'input_path' referenced before assignment
[2025-06-10T12:40:56.916+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/csv_to_snowflake_dag.py", line 70, in process_marketing_data
    raise e
  File "/opt/airflow/dags/csv_to_snowflake_dag.py", line 65, in process_marketing_data
    load_csv_to_snowflake(load_date)
  File "/opt/airflow/scripts/pyspark_jobs/csv_to_ods.py", line 61, in load_csv_to_snowflake
    input_path = os.path.join(input_path, f"Date={latest_date}")
UnboundLocalError: local variable 'input_path' referenced before assignment
[2025-06-10T12:40:56.929+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=marketing_performance_to_snowflake, task_id=process_marketing_data, execution_date=20250610T123937, start_date=20250610T124053, end_date=20250610T124056
[2025-06-10T12:40:56.941+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1092 for task process_marketing_data (local variable 'input_path' referenced before assignment; 1735)
[2025-06-10T12:40:56.971+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-10T12:40:56.994+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
